name: Build Release
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  build:
    permissions: 
      issues: write
      pull-requests: write
      security-events: write
      contents: read
      id-token: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
        
      - name: Setup JDK with Maven
        uses: actions/setup-java@v3
        with:
          distribution: microsoft
          java-version: 17
      
      - name: Build release package
        run: mvn -B clean install

      - name: Endor Labs Scan
        uses: endorlabs/github-action@v1.1.2
        with:
          namespace: "shane-demo"
          enable_pr_comments: true
          scan_dependencies: true
          scan_secrets: true
          enable_github_action_token: false
          scan_summary_output_type: "table"
          api_key: ${{ secrets.ENDOR_API_CREDENTIALS_KEY }}
          api_secret: ${{ secrets.ENDOR_API_CREDENTIALS_SECRET }}
          sarif_file: endor-labs.sarif
      
      - name: Upload SARIF to github
        uses: github/codeql-action/upload-sarif@9885f86fab4879632b7e44514f19148225dfbdcd
        with:
          sarif_file: endor-labs.sarif
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: endorlabs-java-webapp-demo
          path: |
            target/endor-java-webapp-demo.jar
        
      
